--- 
title: "The Nutrients - Chlorophyll-a Relationship in Utah Lake, Utah."
author:
  - name: Danisa Dolder
    email: danisadolder@gmail.com
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: article
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
abstract: Utah Lake (UL) is a body of fresh water used for irrigation, recreation, and potable water supply. The first pioneer settlements that found the necessary water resources to live in this arid area produced a change in land use, impacting aquatic ecosystems. Increased pollution due to algal blooms is a problem in UL. In search of a solution, the Utah Department of Water Quality (DWQ) has been working in water quality data collection. In this project, I analyzed if there is a relationship between all these parameters and the algal bloom, measured by the chlorophyll-a.
description: "CEEN 594R-001 Term Project"
---

# Introduction

Phosphorous influences algal blooms in Utah Lake, but the effect of other pollutants and environmental parameters-including nitrogen and dissolved oxygen-are not clearly understood. In this project, I analyzed if there is a relationship between all these parameters and the algal bloom, measured by the chlorophyll-a. Because algal blooms are more common in the Summer, the data will be categorized by month and by season. The data for this project is taken from the Ambient Water Quality Monitoring System (AWQMS) of the Utah Department of Environmental Quality (DEQ). This system has data from 1989 until today, but these data are more consistent in recent years. For this project, I will use the available data for the years 2017, 2018, and 2019.
